// Auto-generated from decision_log_hackweek.csv — the Hackweek workflow & decision-log process log.
export const HACKWEEK_ENTRIES = [
  {
    "id": "HWK-WDL-001",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Framing",
    "decision": "Decided on the hack-week goal",
    "context": "Need a clear north star before building anything",
    "rationale": "A shared goal aligns the 4-person team and frames every later decision",
    "optionsConsidered": "Leave goal loose; focus only on AI; focus only on the decision log",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-002",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Framing",
    "decision": "Grouped pain points into two themes: workflow-capture needs & decision-log needs",
    "context": "Brainstormed pains were scattered",
    "rationale": "Two clean themes map to the two deliverables and the readout",
    "optionsConsidered": "Keep flat list; group by team; group by severity",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — pain point board"
  },
  {
    "id": "HWK-WDL-003",
    "date": "2026-06-10",
    "status": "Deprecated",
    "subject": "Framing",
    "decision": "Defined initial problem statement",
    "context": "Needed a crisp problem to anchor scope",
    "rationale": "v1 conflated 'reduce' and 'capture' rework — replaced by HWK-WDL-004",
    "optionsConsidered": "n/a",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-004",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Framing",
    "decision": "Iterated / refined the problem statement",
    "context": "v1 read awkwardly",
    "rationale": "Tighter wording separates capturing workflow + rationale from reducing rework",
    "optionsConsidered": "Keep v1; several variants",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-005",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Framing",
    "decision": "Determined project scope (in / out)",
    "context": "A one-week sprint risks drifting into building",
    "rationale": "Naming what's OUT protects pilot time",
    "optionsConsidered": "Broad scope; no explicit out-of-scope",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-006",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Method",
    "decision": "Defined the method skeleton (6 stages)",
    "context": "Needed a backbone to build the week around",
    "rationale": "Trigger > Assemble > Capture > Validate > AI pass > Log & handoff covers capture, AI, and decisions",
    "optionsConsidered": "Fewer stages; linear checklist",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-007",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Method",
    "decision": "Defined roles & rituals (incl. facilitator / scribe split)",
    "context": "Capture sessions fail if one person probes and types",
    "rationale": "Splitting facilitator and scribe keeps questions deep and capture accurate",
    "optionsConsidered": "Single capturer; rotate freely",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-008",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Method",
    "decision": "Designed the capture session format",
    "context": "Needed a repeatable session structure",
    "rationale": "A set format makes the method reusable, not ad hoc",
    "optionsConsidered": "Freeform sessions",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-009",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Decided who owns the decision log & where it lives",
    "context": "Logs die when ownership and home are unclear",
    "rationale": "Scribe owns it; one home (FigJam) so entries are never scattered",
    "optionsConsidered": "Anyone edits; multiple homes",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-010",
    "date": "2026-06-10",
    "status": "Descoped",
    "subject": "Pilot",
    "decision": "Voted on pilot workflow: vacation outfit picker",
    "context": "Needed a low-stakes pilot to test the method",
    "rationale": "Fun, tacit-rich, lots of exceptions — later simplified at HWK-WDL-024",
    "optionsConsidered": "Coffee pour-over; group trip; sandwich shop",
    "decisionOwner": "Team (vote)",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-011",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Elicitation",
    "decision": "Created the elicitation question bank",
    "context": "Scribe / facilitator need prompts to surface tacit steps",
    "rationale": "Pulls exceptions, decisions, paper, and pain out of an SME",
    "optionsConsidered": "Improvise questions live",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-012",
    "date": "2026-06-10",
    "status": "Descoped",
    "subject": "Workflow template",
    "decision": "Built workflow template as bubble / node flows",
    "context": "First attempt at the workflow artifact",
    "rationale": "Hard to capture dense detail live — changed at HWK-WDL-013",
    "optionsConsidered": "n/a",
    "decisionOwner": "Team",
    "workflowStep": "Workflow template",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-013",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Workflow template",
    "decision": "Changed workflow template to a table format",
    "context": "Bubble flows too loose for dense capture",
    "rationale": "A table captures lanes consistently",
    "optionsConsidered": "Keep bubble flows; service-blueprint swimlanes",
    "decisionOwner": "Team",
    "workflowStep": "Workflow template",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-014",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Workflow template",
    "decision": "Decided on a workflow info / metadata header",
    "context": "Each capture needs provenance",
    "rationale": "Captures workflow name, SME, owner, date, log link",
    "optionsConsidered": "No header",
    "decisionOwner": "Team",
    "workflowStep": "Template header",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-015",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Workflow template",
    "decision": "Decided workflow rows / columns + descriptions",
    "context": "Needed agreed lanes and step columns",
    "rationale": "Lanes: step, actor, co-stars, system, context, branches, impact, exceptions, pain, AI x2",
    "optionsConsidered": "Fewer lanes; different ordering",
    "decisionOwner": "Team",
    "workflowStep": "Workflow template",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-016",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Decided the decision-log statuses",
    "context": "Need lifecycle states for entries",
    "rationale": "Proposed, Under review, Prioritized, Future state, Rejected, Descoped, Active, Deprecated",
    "optionsConsidered": "Minimal 3-status set",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — status table"
  },
  {
    "id": "HWK-WDL-017",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Decided the ID guide format",
    "context": "Need stable, sortable IDs",
    "rationale": "Project code + workflow code + chronological number (HWK-WDL-001)",
    "optionsConsidered": "Date-based IDs; plain counter",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — ID guide"
  },
  {
    "id": "HWK-WDL-018",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Built decision-log rows / columns + descriptions",
    "context": "Need the log artifact itself",
    "rationale": "Columns: ID, Date, Status, Subject, Decision, Context, Rationale, Options, Owner, Step, Link",
    "optionsConsidered": "Fewer columns",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — this table"
  },
  {
    "id": "HWK-WDL-019",
    "date": "2026-06-10",
    "status": "Descoped",
    "subject": "Pilot",
    "decision": "Started flushing pilot-1 flow context & assigned roles",
    "context": "Began mapping the vacation outfit picker",
    "rationale": "Abandoned when the pilot pivoted at HWK-WDL-024",
    "optionsConsidered": "n/a",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 1",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-020",
    "date": "2026-06-10",
    "status": "Descoped",
    "subject": "Pilot",
    "decision": "Defined pilot-1 functionality (onboarded; weather + AI; itinerary > outfits)",
    "context": "Needed app assumptions to map the flow",
    "rationale": "Replaced by the simpler direction at HWK-WDL-026",
    "optionsConsidered": "n/a",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 1",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-021",
    "date": "2026-06-10",
    "status": "Descoped",
    "subject": "Pilot",
    "decision": "Worked through pilot-1 workflow; made step decisions along the way",
    "context": "Live capture of the vacation flow",
    "rationale": "Abandoned at the pivot; some learnings carried over",
    "optionsConsidered": "n/a",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 1",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-022",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Workflow template",
    "decision": "Split the AI lane into two rows: 'pie in the sky' + 'scoped & decided'",
    "context": "One AI row blurred ideation and decision",
    "rationale": "Two passes separate widening options from committing; pass 2 generates log entries",
    "optionsConsidered": "Single AI row",
    "decisionOwner": "Team",
    "workflowStep": "Template — AI rows",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-023",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Created a 'parking lot' to capture decisions for the log",
    "context": "Decisions surfaced mid-capture were getting lost",
    "rationale": "Park them live, retro-log after — capture fast, structure later",
    "optionsConsidered": "Log live (too slow); skip logging",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-024",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Pilot",
    "decision": "DESCOPE: simplified the pilot to a 'Clueless'-style simpler app",
    "context": "Vacation version too complex; risk of running out of time",
    "rationale": "A simpler scope still proves the method within the week",
    "optionsConsidered": "Push through complex version; drop the pilot entirely",
    "decisionOwner": "Team",
    "workflowStep": "Pilot",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-025",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Presentation",
    "decision": "Decided to include the Clueless closet scene in the final presentation",
    "context": "Watched it for context; strong framing device",
    "rationale": "Memorable; communicates the concept to stakeholders instantly",
    "optionsConsidered": "No media; a different reference",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam / presentation"
  },
  {
    "id": "HWK-WDL-026",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Pilot",
    "decision": "Defined new pilot 'how it works': one-day outfit generator that checks weather and generates",
    "context": "Needed simpler functionality post-descope",
    "rationale": "Single-day, weather-aware generation is enough to exercise the method",
    "optionsConsidered": "Keep the multi-day trip flow",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 2",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-027",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Pilot",
    "decision": "Started reworking the workflow table from the beginning for pilot 2",
    "context": "New direction needs a fresh capture",
    "rationale": "A clean restart avoids dragging vacation-flow assumptions along",
    "optionsConsidered": "Edit the old table in place",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 2",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-028",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Pilot",
    "decision": "Created a quick mockup for visual reference",
    "context": "Needed something visual to anchor the flow",
    "rationale": "A rough mockup makes the generated-outfit concept concrete",
    "optionsConsidered": "No mockup; high-fidelity design",
    "decisionOwner": "Team",
    "workflowStep": "Pilot 2",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-029",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Workflow template",
    "decision": "Added an 'opportunities / notes' row under pain points",
    "context": "Pain points implied ideas worth capturing separately",
    "rationale": "Keeps improvement ideas next to the friction that sparked them",
    "optionsConsidered": "Fold into pain points; fold into AI pass 1",
    "decisionOwner": "Team",
    "workflowStep": "Template — new row",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-030",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Decided to retro-log decisions into the decision log",
    "context": "Many decisions were made before the log existed",
    "rationale": "Backfills the record so nothing's lost — and proves the ritual",
    "optionsConsidered": "Don't backfill",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — this log"
  },
  {
    "id": "HWK-WDL-031",
    "date": "2026-06-10",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Added a 'Subject' column to the decision log",
    "context": "As the log grows, free-text searching the Decision column is unreliable",
    "rationale": "A controlled subject tag lets you filter by area; pairs with Status without overlapping Workflow Step",
    "optionsConsidered": "Rely on text search; reuse Workflow Step; free-text category",
    "decisionOwner": "Team",
    "workflowStep": "Decision log template",
    "otherLink": "FigJam — this log"
  },
  {
    "id": "HWK-WDL-032",
    "date": "2026-06-10",
    "status": "Future state",
    "subject": "Decision log",
    "decision": "Prompt-driven decision-log populater: drop in raw parking-lot notes and have AI draft structured entries",
    "context": "Retro-logging by hand is accurate but slow; the parking-lot-to-log step is the friction point",
    "rationale": "AI drafts entries (decision, context, rationale, options, suggested status / subject) for human review — capture fast, structure automatically",
    "optionsConsidered": "Keep manual retro-logging; a rigid template form; no parking-lot step",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam — parking lot"
  },
  {
    "id": "HWK-WDL-033",
    "date": "2026-06-11",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Capture decisions live on post-it notes during the workshop (not a second table or inline workflow rows)",
    "context": "Needed to log decisions in the moment during a live session without slowing it down; tried three methods",
    "rationale": "Post-its are flexible and can be moved / clustered; capture a minimal field set live (Date, Status, Decision, Rationale, optional Options) and structure into the full log after",
    "optionsConsidered": "A second smaller notes table; notes inline as a workflow row; post-it notes (chosen)",
    "decisionOwner": "Team",
    "workflowStep": "",
    "otherLink": "FigJam"
  },
  {
    "id": "HWK-WDL-034",
    "date": "2026-06-11",
    "status": "Active",
    "subject": "Decision log",
    "decision": "Cap AI pass-2 at 2-4 logged decisions per pass",
    "context": "AI pass 2 can produce a scoped call for every step, risking log bloat",
    "rationale": "Fewer, higher-value decisions keep the log readable and focused — aligns with the 'keep it lightweight' guardrail",
    "optionsConsidered": "Log every step's AI call; no cap; 2-4 per pass (chosen)",
    "decisionOwner": "Team",
    "workflowStep": "Template — AI pass 2",
    "otherLink": "FigJam"
  }
];
